### ISSUE TITLE
Background light

### ISSUE THREAD

**Issue by SchneHa** [iEduard/FritzMeter_ArduinoYun#10]
I think it's a good idea to limit the current through LED(s). I took a 390 Ohm resistance and a current limiting diode in series with the LED(s). One resistor in GND line is sufficient. I use 2 diodes in GPIO line(s).

**Comment by iEduard** [comment]
Thank you for the feedback. I forgot to put them in completely. I added them to the schematic.
 
Depending on the different LED's current Requirements, it is maybe better to split them and put them on one gpio each.

**Comment by iEduard** [comment]
Fixed the schematics and updated the readme
