### ISSUE TITLE
Toggle LEDs

### ISSUE THREAD

**Issue by SchneHa** [iEduard/FritzMeter_ArduinoYun#9]
Switch LEDs as illumination for the instruments  on and off with a momentary push button.

**Comment by iEduard** [comment]
The https://github.com/iEduard/FritzMeter_RaspberryPi/blob/backlight/Software/Background_Light.py script was updated in the branch. 

Script was tested with the pi 4.

**Comment by SchneHa** [comment]
It works GREAT even with Pi Zero with GPIO27 for button and GPIO17 for LED.

**Comment by iEduard** [comment]
Merged the Branch in to the main branch.
README was updated,
HW description was added
LED control script was updated with an additional LED.
